name: wordpress

services:

  wordpress:
    container_name: wordpress
    image: wordpress:6.9.0-php8.3-apache
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: 192.168.122.108:3307
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: strongpassword
      WORDPRESS_ADMIN_EMAIL: admin@example.com
      WORDPRESS_TITLE: HA Example
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - "80:80"
