all:
  vars:
    deploy_database: false
    mariadb_is_primary: false
    deploy_wordpress: false
    deploy_load_balancer: false
    debug: true
local:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/senec-ansible
    ansible_become_password: "1234"
    ansible_become_method: "sudo"

    mariadb_root_password: password

    mariadb_wordpress_username: wordpress
    mariadb_wordpress_password: wordpress_password
    mariadb_wordpress_database_name: wordpress

    mariadb_cluster_primary_ip_internal: 192.168.122.108

    maxscale_username: maxscale
    maxscale_password: maxscale_password

    wordpress_username: 'test'
    wordpress_password: 'test'
    wordpress_email: 'test@localhost.dev'
    wordpress_domain: 'http://192.168.122.108'

    traefik_email: 'soerenklein98@gmail.com'
  hosts:
    vm1:
      ansible_host: 192.168.122.108
      ip_internal: 192.168.122.108
      ip_external: 192.168.122.66

      deploy_database: true
      deploy_wordpress: true
      deploy_load_balancer: true

      mariadb_server_id: 1
      mariadb_is_primary: true
    vm2:
      ansible_host: 192.168.122.100
      ip_internal: 192.168.122.100

      deploy_database: true
      deploy_wordpress: true

      mariadb_server_id: 2
production:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/senec-ansible
  hosts:
    web1:
      ansible_host: 95.216.155.105
      ip_internal: 10.0.0.3
      deploy_database: true
      deploy_wordpress: true

      mariadb_is_primary: true
      mariadb_server_id: 3
    web2:
      ansible_host: 77.42.81.6
      ip_internal: 10.0.0.5
      deploy_database: true
      deploy_wordpress: true

      mariadb_server_id: 5
    web3:
      ansible_host: 37.27.4.181
      ip_internal: 10.0.0.4
      deploy_database: true
      deploy_wordpress: true

      mariadb_server_id: 4
    LB:
      ansible_host: 77.42.28.50
      ip_internal: 10.0.0.2
      deploy_load_balancer: true
